apiVersion: v1
kind: Service
metadata:
  name: xxl-job-service
  namespace: lilishop-middleware
  labels:
    app.kubernetes.io/name: xxl-job-service
    app.kubernetes.io/instance: distributed-task
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: lilishop
    tier: "middleware"
spec:
  type: NodePort
  ports:
    - name: "9001"
      port: 9001
      nodePort: 30001
      targetPort: xxl9001
  selector:
    lilishop.service: xxl-job
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xxl-job
  namespace: lilishop-middleware
  labels:
    app.kubernetes.io/name: xxl-job
    app.kubernetes.io/instance: distributed-task
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: lilishop
    tier: "middleware"
spec:
  serviceName: xxl-job
  replicas: 1
  selector:
    matchLabels:
      lilishop.service: xxl-job
  template:
    metadata:
      labels:
        lilishop.service: xxl-job
    spec:
      initContainers:
        - name: init-mysql
          image: pubrepo.jiagouyun.com/demo/demo-lilishop-busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nslookup mysql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mysql; sleep 2; done",
            ]
      containers:
        - env:
            - name: PARAMS
              value: --spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?Unicode=true&characterEncoding=UTF-8  --spring.datasource.username=root --spring.datasource.password=lilishop --server.port=9001
          image: pubrepo.jiagouyun.com/demo/demo-lilishop-xxl-job:2.3.0
          name: xxl-job
          ports:
            - name: xxl9001
              containerPort: 9001
          resources: {}
          volumeMounts:
            - mountPath: /data/applogs
              name: vol-xxl-job-logs
      restartPolicy: Always
      volumes:
        - name: vol-xxl-job-logs
          hostPath:
            path: /root/docker/kubernetes/data/middleware/xxl-job
            type: Directory
