name: Build and push lilishop java demo images

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: Linux-java-0708c922d4bf4dab90192af21a5e94f25f35379430c7d269d18c20fe0d77
          restore-keys: |
            Linux-java-

#      - name: Log in to the Docker registry
#        uses: docker/login-action@v2
#        with:
#          registry: ${{ vars.DOCKER_REGISTRY }}
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build with Maven
        run: |
         cd ./src/lilishop
         docker login ${{ vars.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
         mvn clean package docker:build  -DskipTests  -DpushImage
